### ISSUE TITLE
Logo with shadow field in backend

### ISSUE THREAD

**Issue by J0hn5mith** [gloggi/abteilungs-homepages#12]
The font in the header has a shadow. If the logo does not it looks ugly. On the other hand, we used the logo without a shadow for the nav bar. Therefore, we need another field for a logo with a shadow. 

<img width="900" alt="cloudapp annotation 2017-10-04 at 8 11 00 pm" src="https://user-images.githubusercontent.com/856276/31191982-2f69508a-a940-11e7-9878-11d455f82d42.png">

**Comment by carlobeltrame** [comment]
a more pragmatic solution would be https://stackoverflow.com/a/13624469
unfortunately not supported in IE: http://caniuse.com/#feat=css-filters

**Comment by carlobeltrame** [comment]
But SVG filters are supported in all browsers: https://caniuse.com/#feat=svg-filters

**Comment by J0hn5mith** [comment]
I like the approach of svg filter the best. I'll give this a try.

**Comment by carlobeltrame** [comment]
It's already implemented, see #17
