### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by carlobeltrame** [gloggi/abteilungs-homepages#41]

**Comment by boris85** [comment]
Das ist aus meiner Sicht doch ein ziemlich wichtiges Thema:
![image](https://user-images.githubusercontent.com/381209/40712434-079a93c4-63fe-11e8-854a-96c564315f90.png)

**Comment by carlobeltrame** [comment]
Absolut. Letzter Stand der Besprechung war dass dein Bruder dich mal ansprechen sollte, ob du gerade weisst was man da machen kann.
